<?xml version="1.0"?>
<package format="3">
  <name>sphero_rvr_controllers</name>
  <version>1.0.0</version>
  <description>The sphero_rvr_controllers package</description>

  <license>MIT</license>
  <maintainer email="mppritchard3@hotmail.com">mik-p</maintainer>
  <author email="mppritchard3@hotmail.com">mik p</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>controller_manager</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_twist_joy</exec_depend>
  <exec_depend>twist_mux</exec_depend>
  <exec_depend>interactive_marker_twist_server</exec_depend>
  <exec_depend>sphero_rvr_control</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
