<?xml version="1.0"?>
<package format="3">
  <name>sphero_rvr_bringup</name>
  <version>1.0.0</version>
  <description>The sphero_rvr_bringup package</description>

  <license>MIT</license>
  <maintainer email="mppritchard3@hotmail.com">mik-p</maintainer>
  <author email="mppritchard3@hotmail.com">mik p</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime dependencies -->
  <exec_depend>sphero_rvr_control</exec_depend>
  <exec_depend>sphero_rvr_controllers</exec_depend>
  <exec_depend>rosbridge_server</exec_depend>
  <exec_depend>rvr_autokit_driver</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
