<?xml version="1.0"?>
<package format="3">
  <name>sphero_rvr_description</name>
  <version>1.0.0</version>
  <description>The sphero_rvr_description package</description>

  <license>MIT</license>
  <maintainer email="mppritchard3@hotmail.com">mik-p</maintainer>
  <author email="mppritchard3@hotmail.com">mik p</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>urg_node</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
